units_type: character
feature_source: librosa
feature_type: logmel
data:
  name: aishell
  vocab: data/aishell/lang_char.txt
  left_context_width: 3
  right_context_width: 0
  feature_dim: 128
  subsample: 3
  apply_cmvn: False
  max_input_length: 410  # 最大490
  max_target_length: 42  # 最大44
  batch_size: 1
  short_first: False
  shuffle: True
  train: data/aishell/train.csv
  dev: data/aishell/dev.csv
  test: data/aishell/test.csv
  ignore_id: -1
model:
  enc:
    input_size: 512
    output_size: 512
    attention_heads: 8
    linear_units: 512
    num_blocks: 1
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer:
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    normalize_before: True
    concat_after: False
    positionwise_layer_type: linear
    positionwise_conv_kernel_size: 1
    padding_idx: -1
  dec:
    input_size: 4233
    output_size: 512
    attention_heads: 8
    linear_units: 512
    num_blocks: 1
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: embed
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    normalize_before: True
    concat_after: False
    positionwise_layer_type: linear
    positionwise_conv_kernel_size: 1
    padding_idx: -1
  joint:
    vocab_size: 4233
    encoder_output_size: 512
    decoder_output_size: 512
    joint_space_size: 512
    joint_activation_type: tanh
  mask:
    encoder_left_mask: 10
    encoder_right_mask: 2
    decoder_left_mask: 2
training:
  exp_name: espnet_aishell_10_2_2
  load_model: False
  load_encoder: False
  load_decoder: False
  eval_or_not: True
  seed: 1
  num_gpu: 1
  epochs: 30
  max_grad_norm: 200
  visualization: True
  show_interval: 100
  save_model: 2e_2d_512
optim:
  type: sgd
  lr: 0.00025
  momentum: 0.9
  decay_ratio: 0.1
  weight_decay: 0
  begin_to_adjust_lr: 0
