units_type: character
feature_source: librosa
feature_type: logmel
data:
    name: joint
    vocab: data/joint/grapheme_table.txt
    left_context_width: 3
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: False
    max_input_length: 500  # 最大490
    max_target_length: 50  # 最大44
    batch_size: 8
    short_first: False
    shuffle: False
    train: data/joint/train
    dev: data/joint/dev
    test: data/joint/test
model:
    type: transducer
    enc:
        type: attention
        max_input_length: 500
        hidden_size:
        output_size:
        d_inner: 1024
        n_head: 8
        d_model: 512
        d_head: 64
        n_layer: 18
    dec:
        type: attention
        max_target_length: 50
        hidden_size:
        output_size:
        d_inner: 1024
        n_head: 8
        d_model: 512
        d_head: 64
        n_layer: 2
    joint:
        input_size: 1024
        inner_size: 2048
    vocab_size: 6485
    share_weight: False
    feature_dim:
    dropout: 0.1
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 1
    num_gpu: 1
    epochs: 30
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: 10e_2d
optim:
    type: sgd
    lr: 0.00025
    momentum: 0.9
    decay_ratio: 0.6
    weight_decay: 0
    begin_to_adjust_lr: 10
