units_type: character
feature_source: kaldi
feature_type: fbank_40
data:
    name: thchs30
    vocab: data/thchs30/grapheme_table.txt
    left_context_width: 3
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: False
    max_input_length: 500
    max_target_length: 50
    batch_size: 1
    short_first: True
    shuffle: False
    train: data/thchs30/train
    dev: data/thchs30/dev
    test: data/thchs30/test
model:
    type: transducer
    enc:
        type: attention
        max_input_length: 500
        hidden_size:
        output_size:
        d_inner: 1024
        n_head: 8
        d_model: 160
        d_head: 20
        n_layer: 8
    dec:
        type: attention
        max_target_length: 50
        hidden_size:
        output_size:
        d_inner: 1024
        n_head: 8
        d_model: 512
        d_head: 64
        n_layer: 2
    joint:
        input_size: 672
        inner_size: 2048
    vocab_size: 2884
    share_weight: False
    feature_dim:
    dropout: 0.1
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 1
    num_gpu: 1
    epochs: 20
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: test
optim:
    type: sgd
    lr: 0.00025
    momentum: 0.9
    decay_ratio: 0.5
    weight_decay: 0
    begin_to_adjust_lr: 10
